# SOME DOCUMENTATION
# Hosts mapped to "None" were grouped into small clades and were deleted.

# "location" indicates where the soil was sampled from.
# This means that greenhouse-grown communities still get mapped to a location as long as the soil wasourced from a field.

data_path: "../data"
plotting_dir: "../data/plots"
processed_files: "processed_files.yml"

levels:
  2: "phylum"
  3: "class"
  4: "order"
  5: "family"
  6: "genus"

inoculum_studies:
  - "swift2024drought"
  - "moore2023microbial"
  - "munoz-ucros2021drought"

drought_studies:
  - "santos-medellin2021prolonged"
  - "simmons2020drought"
  - "fitspatrick2017assembly"
  - "hoefle2024oak"
  - "faist2022potato"
  - "santos-medellin2017drought"
  - "azarbad2020four"
  - "naylor2017drought"
  - "xu2018drought"
  - "bandopadhyay2024disentangling"

# DROUGHT STUDIES
# ---

xu2018drought:
  full_name: "Xu et al. (2018)"
  amplicon_length: 300
  filters:
    - "lambda row: 'Soil' not in str(row['Env Material [sample]'])"
    - "lambda row: 'bulk soil' not in str(row['Env Medium [sample]'])"
    - "lambda row: 'Positive' not in str(row['Env Material [sample]'])"
  treatment_col: "Treatment [sample]"
  treatments:
    "Pre_flowering": "Pre_flowering"
    "Post_flowering": "Post_flowering"
    "Control": "Control"
    "Water": "Control"
    "Drought": "Drought"
  host_col: "Host [sample]"
  hosts:
    "Sorghum bicolor": "PACMAD clade"
  hosts_ungrouped:
    "Sorghum bicolor": "Sorghum bicolor"
  # Required since drought is only applied pre_flowering or post_flowering
  timepoint_col: "Title"
  tp_regex: "TP(?P<tp>\\d+)"
  drought_timepoints:
    Pre_flowering:
      max_tp: 8
    Post_flowering:
      min_tp: 10
  location: "California"
  soil_type: "Field"
  primers: "341F,785R"
  regions: "V3-V4"

santos-medellin2021prolonged:
  full_name: "Santos-Medellín et al. (2021)"
  amplicon_length: 250
  filters: {}
  treatment_col: "Water Regime [sample]"
  treatments:
    "Drought 10 days": "Drought"
    "Drought 20 days": "Drought"
    "Drought 30 days": "Drought"
    "Drought 30 days": "Drought"
    "Watered Control": "Control"
    "Watered Control Training": "Control"
    "Control Training": "Control"
    "Drought 21 days": "Drought"
  host_col: "Host [sample]"
  hosts:
    "Oryza sativa": "BOP clade"
  hosts_ungrouped:
    "Oryza sativa": "Oryza sativa"
  location: "California"
  soil_type: "Field"
  primers: "515F,806R"
  regions: "V4"

hoefle2024oak:
  full_name: "Hoefle et al. (2024)"
  amplicon_length: 300
  filters:
    - "lambda row: str(row['Env Local Scale [sample]']) == 'rhizosphere'"
    - "lambda row: 'fungi' not in str(row['Name'])"
  treatment_col: "Climate Environment [sample]"
  treatments:
    "soil moisture 15 %": "Drought"
    "soil moisture 60 %": "Control"
  host_col: "Host [sample]"
  hosts:
    "Quercus robur": "Fabids"
  hosts_ungrouped:
    "Quercus robur": "Quercus robur"
  location: "Greenhouse"
  soil_type: "Sand"
  primers: "515F,806R"
  regions: "V4"

bandopadhyay2024disentangling:
  full_name: "Bandopadhyay et al. (2024)"
  amplicon_length: 300
  filters:
    - "lambda row: 'unplanted' not in str(row['Env Local Scale [sample]'])"
    - "lambda row: 'pre-drought' not in str(row['Treatment [sample]'])"
    # Remove negative control
    - "lambda row: 'not applicable' not in str(row['Treatment [sample]'])"
  treatment_col: "Treatment [sample]"
  treatments:
    "drought": "Drought"
    "well-watered": "Control"
  host_col: "Host [sample]"
  hosts:
    "bean": "Fabids"
    "switchgrass": "PACMAD clade" 
  hosts_ungrouped:
    "bean": "Phaseolus vulgaris"
    "switchgrass": "Panicum virgatum"
  location: "Michigan"
  soil_type: "Field"
  primers: "515F,806R"
  regions: "V4"

santos-medellin2017drought:
  full_name: "Santos-Medellín et al. (2017)"
  amplicon_length: 250
  filters:
    - "lambda row: str(row['Root Compartment [sample]']) != 'BulkSoil'"
  treatment_col: "Watering Regm [sample]"
  treatments:
    "Drought": "Drought"
    "Watered": "Control"
  host_col: "Host [sample]"
  hosts:
    "Oryza glaberrima": "BOP clade"
    "Oryza sativa": "BOP clade"
  hosts_ungrouped:
    "Oryza glaberrima": "Oryza glaberrima"
    "Oryza sativa": "Oryza sativa"
  location: "California"
  soil_type: "Field"
  primers: "515F,806R"
  regions: "V4"

faist2022potato:
  full_name: "Faist et al. (2023)"
  amplicon_length: 300
  filters:
    - "lambda row: 'fungi' not in str(row['Library Name'])"
    - "lambda row: 'mock community' not in str(row['Name'])"
    - "lambda row: 'no host' not in str(row['Host [sample]'])"
    # Download only amplicon data (no shotgun metagenomics)
    - "lambda row: str(row['Instrument']) == 'Illumina MiSeq'"
  treatment_col: "Watering Regm [sample]"
  treatments:
    "drought": "Drought"
    "irrigated": "Control"  
  host_col: "Host [sample]"
  hosts:
    "Solanum tuberosum.*": "Asterids"
  hosts_ungrouped:
    "Solanum tuberosum.*": "Solanum tuberosum"
  location: "Greenhouse"
  soil_type: "Clay"
  primers: "799F,1175R"
  regions: "V5-V7"  

azarbad2020four:
  full_name: "Azarbad et al. (2020)"
  amplicon_length: 250
  filters:
    - "lambda row: 'ITS' not in str(row['Name'])"
    - "lambda row: 'LEAF' not in str(row['Library Name'])"
    - "lambda row: 'Leaf' not in str(row['Library Name'])"
  treatment_col: "Title"
  treatments:
    ".*_5_.*_(?:ITS|16S)$": "Drought"
    ".*_20_.*_(?:ITS|16S)$": "Drought"
    ".*_30_.*_(?:ITS|16S)$": "Control"
    ".*_50_.*_(?:ITS|16S)$": "Control"
  host_col: "Isolation Source [sample]"
  hosts:
    # Placeholder mapping since the host is not mentioned in
    # the metadata, but only in the publication
    "soil": "BOP clade"
  hosts_ungrouped:
    "soil": "Triticum aestivum"
  location: "Saskatchewan"
  soil_type: "Field"
  primers: "520F,799R2"
  regions: "V3-V4"

simmons2020drought:
  full_name: "Simmons et al. (2020)"
  amplicon_length: 300
  filters:
    - "lambda row: str(row['Isolation Source [sample]']) != 'soil'"
  treatment_col: "Treatment_all"
  treatments:
    "Drought": "Drought"
    "Watered": "Control"
  host_col: "Host [sample]"
  hosts:
    "Echinochloa esculenta": "PACMAD clade"
    "Panicum miliaceum": "PACMAD clade"
    # Misspelled in the metadata
    "Penisetum glaucum": "PACMAD clade"
    "Setaria italica": "PACMAD clade"
    "Sorghum bicolor": "PACMAD clade"
  hosts_ungrouped:
    "Echinochloa esculenta": "Echinochloa esculenta"
    "Panicum miliaceum": "Panicum miliaceum"
    "Penisetum glaucum": "Cenchrus americanus"
    "Setaria italica": "Setaria italica"
    "Sorghum bicolor": "Sorghum bicolor"
  location: "California"
  soil_type: "Field"
  primers: "341F,785R"
  regions: "V3-V4"
  link_NCBI_metadata: "Name"
  link_supplemental_metadata: "SampleID"

fitspatrick2017assembly:
  full_name: "Fitzpatrick et al. (2018)"
  amplicon_length: 150
  filters:
    - "lambda row: str(row['Isolation Source [sample]']) != 'live bare soil'"
    - "lambda row: 'analogue' not in str(row['Isolation Source [sample]'])"
    - "lambda row: str(row['treatment']) != 'NA'"
  treatment_col: "treatment"
  treatments:
    "d": "Drought"
    "w": "Control"
  host_col: "Host [sample]"
  hosts:
    "Amaranthus albus": "None"
    "Arctium minus": "Asterids"
    "Asclepias incarnata": "Asterids"
    "Asparagus officinalis": "None"
    "Bromus inermis": "BOP clade"
    "Capsella bursa-pastoris": "Malvids"
    "Cichorium intybus": "Asterids"
    "Convolvulus arvensis": "Asterids"
    "Desmodium canadense": "Fabids"
    "Digitaria ischaemum": "PACMAD clade"
    "Erysimum cheiranthoides": "Malvids"
    "Geum aleppicum": "Fabids"
    "Geum canadense": "Fabids"
    "Lepidium densiflorum": "Malvids"
    "Lolium arundinaceum": "BOP clade"
    "Lotus corniculatus": "Fabids"
    "Malva neglecta": "Malvids"
    "Medicago sativa": "Fabids"
    "Oenothera biennis": "Malvids"
    "Oenothera perennis": "Malvids"
    "Persicaria maculosa": "None"
    "Phalaris arundinacea": "BOP clade"
    "Phleum pratense": "BOP clade"
    "Pilosella piloselloides": "Asterids"
    "Plantago major": "Asterids"
    "Plantago rugelii": "Asterids"
    "Potentilla recta": "Fabids"
    "Silene latifolia": "None"
    "Sisymbrium officinale": "Malvids"
    "Solanum dulcamara": "Asterids"
    "Solidago gigantea": "Asterids"
    "Sonchus arvensis": "Asterids"
    "Sonchus oleraceus": "Asterids"
    "Sporobolus cryptandrus": "PACMAD clade"
    "Sporobolus neglectus": "PACMAD clade"
    "Symphyotrichum ericoides": "Asterids"
    "Thlaspi arvense": "Malvids"
    "Vicia sativa": "Fabids"
    "Vicia tetrasperma": "Fabids"
  hosts_ungrouped:
    "Amaranthus albus": "None"
    "Arctium minus": "Arctium minus"
    "Asclepias incarnata": "Asclepias incarnata"
    "Asparagus officinalis": "None"
    "Bromus inermis": "Bromus inermis"
    "Capsella bursa-pastoris": "Capsella bursa-pastoris"
    "Cichorium intybus": "Cichorium intybus"
    "Convolvulus arvensis": "Convolvulus arvensis"
    "Desmodium canadense": "Desmodium canadense"
    "Digitaria ischaemum": "Digitaria ischaemum"
    "Erysimum cheiranthoides": "Erysimum cheiranthoides"
    "Geum aleppicum": "Geum aleppicum"
    "Geum canadense": "Geum canadense"
    "Lepidium densiflorum": "Lepidium densiflorum"
    "Lolium arundinaceum": "Lolium arundinaceum"
    "Lotus corniculatus": "Lotus corniculatus"
    "Malva neglecta": "Malva neglecta"
    "Medicago sativa": "Medicago sativa"
    "Oenothera biennis": "Oenothera biennis"
    "Oenothera perennis": "Oenothera perennis"
    "Persicaria maculosa": "None"
    "Phalaris arundinacea": "Phalaris arundinacea"
    "Phleum pratense": "Phleum pratense"
    "Pilosella piloselloides": "Pilosella piloselloides"
    "Plantago major": "Plantago major"
    "Plantago rugelii": "Plantago rugelii"
    "Potentilla recta": "Potentilla recta"
    "Silene latifolia": "None"
    "Sisymbrium officinale": "Sisymbrium officinale"
    "Solanum dulcamara": "Solanum dulcamara"
    "Solidago gigantea": "Solidago gigantea"
    "Sonchus arvensis": "Sonchus arvensis"
    "Sonchus oleraceus": "Sonchus oleraceus"
    "Sporobolus cryptandrus": "Sporobolus cryptandrus"
    "Sporobolus neglectus": "Sporobolus neglectus"
    "Symphyotrichum ericoides": "Symphyotrichum ericoides"
    "Thlaspi arvense": "Thlaspi arvense"
    "Vicia sativa": "Vicia sativa"
    "Vicia tetrasperma": "Vicia tetrasperma"
  location: "Ontario"
  soil_type: "Field"
  primers: "515F,808R"
  regions: "V4"
  link_NCBI_metadata: "Name"
  link_supplemental_metadata: "Sample_ID"

naylor2017drought:
  full_name: "Naylor et al. (2017)"
  amplicon_length: 300
  filters:
    - "lambda row: 'Kearney' not in str(row['Library Name'])"
    - "lambda row: 'ITS2' not in str(row['Library Name'])"
    - "lambda row: str(row['Plant Body Site [sample]']) != 'Soil'"
  treatment_col: "Watering Regm [sample]"
  treatments:
    "Drought": "Drought"
    "Control": "Control"
  host_col: "Isolation Source [sample]"
  hosts:
    "Zea mays": "PACMAD clade"
    "Triticum turgidum": "BOP clade"
    "Triticum monococcum": "BOP clade"
    "Triticum aestivum": "BOP clade"
    "Sorghum laxiflorum": "PACMAD clade"
    "Sorghum bicolor": "PACMAD clade"
    "Sorghastrum nutans": "PACMAD clade"
    "Solanum lycopersicum": "Asterids"
    "Secale cereale": "BOP clade"
    "Pennisetum glaucum": "PACMAD clade"
    "Miscanthus sinensis": "PACMAD clade"
    "Hordeum vulgare": "BOP clade"
    "Festuca arundinacea": "BOP clade"
    "Eragrostis tef": "PACMAD clade"
    "Brachypodium distachyon": "BOP clade"
    "Bothriochloa bladhii": "PACMAD clade"
    "Avena sativa": "BOP clade"
  hosts_ungrouped:
    "Zea mays": "Zea mays"
    "Triticum turgidum": "Triticum turgidum"
    "Triticum monococcum": "Triticum monococcum"
    "Triticum aestivum": "Triticum aestivum"
    "Sorghum laxiflorum": "Sorghum laxiflorum"
    "Sorghum bicolor": "Sorghum bicolor"
    "Sorghastrum nutans": "Sorghastrum nutans"
    "Solanum lycopersicum": "Solanum lycopersicum"
    "Secale cereale": "Secale cereale"
    "Pennisetum glaucum": "Cenchrus americanus"
    "Miscanthus sinensis": "Miscanthus sinensis"
    "Hordeum vulgare": "Hordeum vulgare"
    "Festuca arundinacea": "Lolium arundinaceum" # synonyms
    "Eragrostis tef": "Eragrostis tef"
    "Brachypodium distachyon": "Brachypodium distachyon"
    "Bothriochloa bladhii": "Bothriochloa bladhii"
    "Avena sativa": "Avena sativa"
  location: "California"
  soil_type: "Field"
  primers: "341F,785R"
  regions: "V3-V4"

kost2024microbial:
  amplicon_length: 300
  filters:
    - "lambda row: str(row['Isolation Source [sample]']) != 'soil'"
  treatment_col: "Treatment_all"
  treatments:
    "Drought": "Drought"
    "Watered": "Control"
  host_col: "Host [sample]"
  hosts:
    "Echinochloa esculenta": "PACMAD clade"
    "Panicum miliaceum": "PACMAD clade"
    # Misspelled in the metadata
    "Penisetum glaucum": "PACMAD clade"
    "Setaria italica": "PACMAD clade"
    "Sorghum bicolor": "PACMAD clade"
  hosts_ungrouped:
    "Echinochloa esculenta": "Echinochloa esculenta"
    "Panicum miliaceum": "Panicum miliaceum"
    "Penisetum glaucum": "Cenchrus americanus"
    "Setaria italica": "Setaria italica"
    "Sorghum bicolor": "Sorghum bicolor"

# INOCULUM STUDIES
# ---

# This is a NovaSeq study unlike all others which are MiSeq
swift2024drought:
  amplicon_length: 250
  filters:
    # discard slurry samples (they are very similar to the soil samples)
    - "lambda row: 'slurry' not in str(row['Env Medium [sample]'])"
    # keep only late harvest as done in the paper
    - "lambda row: str(row['Harvest Time Point [sample]']) == 'late' or pd.isna(row['Harvest Time Point [sample]'])"
    # Remove ITS samples (these are only labelled for the inoculum samples)
    # For the pthers we have to remove post-processing
    - "lambda row: 'ITS' not in str(row['Title'])"
  inoculum_col: "Soil Inoculum [sample]"
  # Separate based on precipitation gradient in the paper
  inocula:
    "SVR": "DroughtLegacy"
    "HAY": "DroughtLegacy"
    "TLI": "Other"
    "KNZ": "Other"
    "Control": "Other"
  treatment_col: "Drought or Watered"
  treatments:
    "D": "Drought"
    "W": "Control"
  host_col: "Host [sample]"
  hosts:
    "Zea mays": "PACMAD clade"
  hosts_ungrouped:
    "Zea mays": "Zea mays"
  # whether the sample represent an inoculum sample or is plant-associated
  sample_type_col: "Env Medium [sample]"
  sample_types:
    "plant matter": "Plant-associated"
    "soil*": "Inoculum soil"
  link_NCBI_metadata: "Title"
  link_supplemental_metadata: "RepID"
  height_col: "Height_Feb19"

moore2023microbial:
  amplicon_length: 300
  treatment_col: "Water Content Soil [sample]"
  treatments:
    "Well-watered": "Control"
    "Water-limited": "Drought"
  # Dummy column since host s not included so we take it from the paper
  host_col: "Env Local Scale [sample]"
  hosts:
    "Pot": "PACMAD clade"
  hosts_ungrouped:
    "Pot": "Zea mays"
  inoculum_col: "Env Medium [sample]"
  inocula:
    "Inoculum: Agricultural_field": "Other"
    "Inoculum: Forest_soil": "DroughtLegacy"
  # Only one type
  sample_type_col: "Env Broad Scale [sample]"
  sample_types:
    "Greenhouse": "Plant-associated"
  link_NCBI_metadata: "Title"
  link_supplemental_metadata: "Sample_ID"
  match_regex: "(N\\d+)"
  height_col: "Height_cm"

munoz-ucros2021drought:
  amplicon_length: 250
  filters:
    # Not sure what GENEVA stands for
    - "lambda row: str(row['Microbiome [sample]']) != 'GENEVA'"
    # Remove fungal samples
    - "lambda row: 'ITS' not in str(row['Library Name'])"
  treatment_col: "Treatment [sample]"
  treatments:
    "Control": "Control" 
    "Drought": "Drought"
  # Dummy column since host s not included so we take it from the paper
  host_col: "Organism"
  hosts:
    "rhizosphere metagenome": "Fabids"
  hosts_ungrouped:
    "rhizosphere metagenome": "Salix purpurea"
  inoculum_col: "Microbiome [sample]"
  inocula:
    "WET": "Other"
    "DRY": "DroughtLegacy"
    "STERILE": "Other"
    "PREDRY": "None"
    "PREWET": "None"
  sample_type_col: "Microbiome [sample]"
  sample_types:
    "WET": "Plant-associated"
    "DRY": "Plant-associated"
    "STERILE": "Plant-associated"
    "PREDRY": "Inoculum soil"
    "PREWET": "Inoculum soil"
  # I did this manually by adding length increase and length
  # This should be modified to be done in the code
  height_col: "Length"

zhang2022cross:
  amplicon_length: 250
  filters:
    # Remove fungal samples
    - "lambda row: 'F' not in str(row['Name'])"
    - "lambda row: 'Neg' not in str(row['Name'])"
  treatment_col: "Name"
  treatments:
    ".*W.*": "Control"
    ".*D.*": "Drought"
    ".*I.*": "None"
  # Dummy column
  host_col: "Tax ID"
  hosts:
    "410658": "PACMAD clade"
  hosts_ungrouped:
    "410658": "Zea mays"
  inoculum_col: "Name"
  inocula:
    "^A.*": "DroughtLegacy"
    "^O.*": "Other"  
  sample_type_col: "Name"
  sample_types:
    # Contains I
    ".*I.*": "Inoculum soil"
    # Does not contain I
    "^[^I]*$": "Plant-associated" 

colors:
  "Xu et al. (2018)": "#FAC72F"
  "Simmons et al. (2020)": "#504D44"
  "Azarbad et al. (2020)": "#547A5B" 
  "Fitzpatrick et al. (2018)": "#5664A5" 
  "Santos-Medellín et al. (2021)": "#A55664"
  "Santos-Medellín et al. (2017)": "#FA2F53"
  "Hoefle et al. (2024)": "#2FFA55" 
  "Bandopadhyay et al. (2024)": "#2F54FA" 
  "Naylor et al. (2017)": "#52BA65" 
  "Faist et al. (2023)": "#A79357"

  "Asterids": "#66c1a6"
  "Fabids": "#8f9fca"
  "Malvids": "#e68cc1"
  "BOP clade": "#f89267"
  "PACMAD clade": "#a2d85d"
