# SOME DOCUMENTATION
# Hosts mapped to "None" were grouped into small clades and were deleted.

# "location" indicates where the soil was sampled from.
# This means that greenhouse-grown communities still get mapped to a location as long as the soil wasourced from a field.

data_path: "../data"
plotting_dir: "../data/plots"
processed_files: "processed_files.yml"

levels:
  2: "phylum"
  3: "class"
  4: "order"
  5: "family"
  6: "genus"

inoculum_studies:
  - "yue2024host"
  - "moore2023microbial"
  - "munoz-ucros2021drought"
  - "zhang2022cross"
  - "swift2024drought"

drought_studies:
  - "santos-medellin2021prolonged"
  - "simmons2020drought"
  - "fitspatrick2017assembly"
  - "hoefle2024oak"
  - "faist2022potato"
  - "santos-medellin2017drought"
  - "azarbad2020four"
  - "naylor2017drought"
  - "xu2018drought"
  - "bandopadhyay2024disentangling"

# All studies and attributes
yue2024host:
  inoculum_col_name: "Geo Loc Name [sample]"
  normal_inoculum: "China:Suqian City, Jiangsu Province"
  dry_inoculum: "China:Yangli City, Shaanxi Province"
    
moore2023microbial:
  inoculum_col_name: "Env Medium [sample]"
  normal_inoculum: "Inoculum: Agricultural_field"
  dry_inoculum: "Inoculum: Forest_soil"
    
munoz-ucros2021drought:
  inoculum_col_name: "Microbiome [sample]"
  normal_inoculum: "WET"
  dry_inoculum: "DRY"
    
zhang2022cross: "No data"

xu2018drought:
  full_name: "Xu et al. (2018)"
  amplicon_length: 300
  filters:
    - "lambda row: 'Soil' not in str(row['Env Material [sample]'])"
    - "lambda row: 'bulk soil' not in str(row['Env Medium [sample]'])"
    - "lambda row: 'Positive' not in str(row['Env Material [sample]'])"
  treatment_col: "Treatment [sample]"
  treatments:
    "Pre_flowering": "Pre_flowering"
    "Post_flowering": "Post_flowering"
    "Control": "Control"
    "Water": "Control"
    "Drought": "Drought"
  host_col: "Host [sample]"
  hosts:
    "Sorghum bicolor": "PACMAD clade"
  hosts_ungrouped:
    "Sorghum bicolor": "Sorghum bicolor"
  # Required since drought is only applied pre_flowering or post_flowering
  timepoint_col: "Title"
  tp_regex: "TP(?P<tp>\\d+)"
  drought_timepoints:
    Pre_flowering:
      max_tp: 8
    Post_flowering:
      min_tp: 10
  location: "California"
  soil_type: "Field"
  primers: "341F,785R"
  regions: "V3-V4"

santos-medellin2021prolonged:
  full_name: "Santos-Medellín et al. (2021)"
  amplicon_length: 250
  filters: {}
  treatment_col: "Water Regime [sample]"
  treatments:
    "Drought 10 days": "Drought"
    "Drought 20 days": "Drought"
    "Drought 30 days": "Drought"
    "Drought 30 days": "Drought"
    "Watered Control": "Control"
    "Watered Control Training": "Control"
    "Control Training": "Control"
    "Drought 21 days": "Drought"
  host_col: "Host [sample]"
  hosts:
    "Oryza sativa": "BOP clade"
  hosts_ungrouped:
    "Oryza sativa": "Oryza sativa"
  location: "California"
  soil_type: "Field"
  primers: "515F,806R"
  regions: "V4"

hoefle2024oak:
  full_name: "Hoefle et al. (2024)"
  amplicon_length: 300
  filters:
    - "lambda row: str(row['Env Local Scale [sample]']) == 'rhizosphere'"
    - "lambda row: 'fungi' not in str(row['Name'])"
  treatment_col: "Climate Environment [sample]"
  treatments:
    "soil moisture 15 %": "Drought"
    "soil moisture 60 %": "Control"
  host_col: "Host [sample]"
  hosts:
    "Quercus robur": "Fabids"
  hosts_ungrouped:
    "Quercus robur": "Quercus robur"
  location: "Greenhouse"
  soil_type: "Sand"
  primers: "515F,806R"
  regions: "V4"

bandopadhyay2024disentangling:
  full_name: "Bandopadhyay et al. (2024)"
  amplicon_length: 300
  filters:
    - "lambda row: 'unplanted' not in str(row['Env Local Scale [sample]'])"
    - "lambda row: 'pre-drought' not in str(row['Treatment [sample]'])"
    # Remove negative control
    - "lambda row: 'not applicable' not in str(row['Treatment [sample]'])"
  treatment_col: "Treatment [sample]"
  treatments:
    "drought": "Drought"
    "well-watered": "Control"
  host_col: "Host [sample]"
  hosts:
    "bean": "Fabids"
    "switchgrass": "PACMAD clade" 
  hosts_ungrouped:
    "bean": "Phaseolus vulgaris"
    "switchgrass": "Panicum virgatum"
  location: "Michigan"
  soil_type: "Field"
  primers: "515F,806R"
  regions: "V4"

santos-medellin2017drought:
  full_name: "Santos-Medellín et al. (2017)"
  amplicon_length: 250
  filters:
    - "lambda row: str(row['Root Compartment [sample]']) != 'BulkSoil'"
  treatment_col: "Watering Regm [sample]"
  treatments:
    "Drought": "Drought"
    "Watered": "Control"
  host_col: "Host [sample]"
  hosts:
    "Oryza glaberrima": "BOP clade"
    "Oryza sativa": "BOP clade"
  hosts_ungrouped:
    "Oryza glaberrima": "Oryza glaberrima"
    "Oryza sativa": "Oryza sativa"
  location: "California"
  soil_type: "Field"
  primers: "515F,806R"
  regions: "V4"

faist2022potato:
  full_name: "Faist et al. (2023)"
  amplicon_length: 300
  filters:
    - "lambda row: 'fungi' not in str(row['Library Name'])"
    - "lambda row: 'mock community' not in str(row['Name'])"
    - "lambda row: 'no host' not in str(row['Host [sample]'])"
    # Download only amplicon data (no shotgun metagenomics)
    - "lambda row: str(row['Instrument']) == 'Illumina MiSeq'"
  treatment_col: "Watering Regm [sample]"
  treatments:
    "drought": "Drought"
    "irrigated": "Control"  
  host_col: "Host [sample]"
  hosts:
    "Solanum tuberosum.*": "Asterids"
  hosts_ungrouped:
    "Solanum tuberosum.*": "Solanum tuberosum"
  location: "Greenhouse"
  soil_type: "Clay"
  primers: "799F,1175R"
  regions: "V5-V7"  

azarbad2020four:
  full_name: "Azarbad et al. (2020)"
  amplicon_length: 250
  filters:
    - "lambda row: 'ITS' not in str(row['Name'])"
    - "lambda row: 'LEAF' not in str(row['Library Name'])"
    - "lambda row: 'Leaf' not in str(row['Library Name'])"
  treatment_col: "Title"
  treatments:
    ".*_5_.*_(?:ITS|16S)$": "Drought"
    ".*_20_.*_(?:ITS|16S)$": "Drought"
    ".*_30_.*_(?:ITS|16S)$": "Control"
    ".*_50_.*_(?:ITS|16S)$": "Control"
  host_col: "Isolation Source [sample]"
  hosts:
    # Placeholder mapping since the host is not mentioned in
    # the metadata, but only in the publication
    "soil": "BOP clade"
  hosts_ungrouped:
    "soil": "Triticum aestivum"
  location: "Saskatchewan"
  soil_type: "Field"
  primers: "520F,799R2"
  regions: "V3-V4"

simmons2020drought:
  full_name: "Simmons et al. (2020)"
  amplicon_length: 300
  filters:
    - "lambda row: str(row['Isolation Source [sample]']) != 'soil'"
  treatment_col: "Treatment_all"
  treatments:
    "Drought": "Drought"
    "Watered": "Control"
  host_col: "Host [sample]"
  hosts:
    "Echinochloa esculenta": "PACMAD clade"
    "Panicum miliaceum": "PACMAD clade"
    # Misspelled in the metadata
    "Penisetum glaucum": "PACMAD clade"
    "Setaria italica": "PACMAD clade"
    "Sorghum bicolor": "PACMAD clade"
  hosts_ungrouped:
    "Echinochloa esculenta": "Echinochloa esculenta"
    "Panicum miliaceum": "Panicum miliaceum"
    "Penisetum glaucum": "Cenchrus americanus"
    "Setaria italica": "Setaria italica"
    "Sorghum bicolor": "Sorghum bicolor"
  location: "California"
  soil_type: "Field"
  primers: "341F,785R"
  regions: "V3-V4"

fitspatrick2017assembly:
  full_name: "Fitzpatrick et al. (2018)"
  amplicon_length: 150
  filters:
    - "lambda row: str(row['Isolation Source [sample]']) != 'live bare soil'"
    - "lambda row: 'analogue' not in str(row['Isolation Source [sample]'])"
    - "lambda row: str(row['treatment']) != 'NA'"
  treatment_col: "treatment"
  treatments:
    "d": "Drought"
    "w": "Control"
  host_col: "Host [sample]"
  hosts:
    "Amaranthus albus": "None"
    "Arctium minus": "Asterids"
    "Asclepias incarnata": "Asterids"
    "Asparagus officinalis": "None"
    "Bromus inermis": "BOP clade"
    "Capsella bursa-pastoris": "Malvids"
    "Cichorium intybus": "Asterids"
    "Convolvulus arvensis": "Asterids"
    "Desmodium canadense": "Fabids"
    "Digitaria ischaemum": "PACMAD clade"
    "Erysimum cheiranthoides": "Malvids"
    "Geum aleppicum": "Fabids"
    "Geum canadense": "Fabids"
    "Lepidium densiflorum": "Malvids"
    "Lolium arundinaceum": "BOP clade"
    "Lotus corniculatus": "Fabids"
    "Malva neglecta": "Malvids"
    "Medicago sativa": "Fabids"
    "Oenothera biennis": "Malvids"
    "Oenothera perennis": "Malvids"
    "Persicaria maculosa": "None"
    "Phalaris arundinacea": "BOP clade"
    "Phleum pratense": "BOP clade"
    "Pilosella piloselloides": "Asterids"
    "Plantago major": "Asterids"
    "Plantago rugelii": "Asterids"
    "Potentilla recta": "Fabids"
    "Silene latifolia": "None"
    "Sisymbrium officinale": "Malvids"
    "Solanum dulcamara": "Asterids"
    "Solidago gigantea": "Asterids"
    "Sonchus arvensis": "Asterids"
    "Sonchus oleraceus": "Asterids"
    "Sporobolus cryptandrus": "PACMAD clade"
    "Sporobolus neglectus": "PACMAD clade"
    "Symphyotrichum ericoides": "Asterids"
    "Thlaspi arvense": "Malvids"
    "Vicia sativa": "Fabids"
    "Vicia tetrasperma": "Fabids"
  hosts_ungrouped:
    "Amaranthus albus": "None"
    "Arctium minus": "Arctium minus"
    "Asclepias incarnata": "Asclepias incarnata"
    "Asparagus officinalis": "None"
    "Bromus inermis": "Bromus inermis"
    "Capsella bursa-pastoris": "Capsella bursa-pastoris"
    "Cichorium intybus": "Cichorium intybus"
    "Convolvulus arvensis": "Convolvulus arvensis"
    "Desmodium canadense": "Desmodium canadense"
    "Digitaria ischaemum": "Digitaria ischaemum"
    "Erysimum cheiranthoides": "Erysimum cheiranthoides"
    "Geum aleppicum": "Geum aleppicum"
    "Geum canadense": "Geum canadense"
    "Lepidium densiflorum": "Lepidium densiflorum"
    "Lolium arundinaceum": "Lolium arundinaceum"
    "Lotus corniculatus": "Lotus corniculatus"
    "Malva neglecta": "Malva neglecta"
    "Medicago sativa": "Medicago sativa"
    "Oenothera biennis": "Oenothera biennis"
    "Oenothera perennis": "Oenothera perennis"
    "Persicaria maculosa": "None"
    "Phalaris arundinacea": "Phalaris arundinacea"
    "Phleum pratense": "Phleum pratense"
    "Pilosella piloselloides": "Pilosella piloselloides"
    "Plantago major": "Plantago major"
    "Plantago rugelii": "Plantago rugelii"
    "Potentilla recta": "Potentilla recta"
    "Silene latifolia": "None"
    "Sisymbrium officinale": "Sisymbrium officinale"
    "Solanum dulcamara": "Solanum dulcamara"
    "Solidago gigantea": "Solidago gigantea"
    "Sonchus arvensis": "Sonchus arvensis"
    "Sonchus oleraceus": "Sonchus oleraceus"
    "Sporobolus cryptandrus": "Sporobolus cryptandrus"
    "Sporobolus neglectus": "Sporobolus neglectus"
    "Symphyotrichum ericoides": "Symphyotrichum ericoides"
    "Thlaspi arvense": "Thlaspi arvense"
    "Vicia sativa": "Vicia sativa"
    "Vicia tetrasperma": "Vicia tetrasperma"
  location: "Ontario"
  soil_type: "Field"
  primers: "515F,808R"
  regions: "V4"

naylor2017drought:
  full_name: "Naylor et al. (2017)"
  amplicon_length: 300
  filters:
    - "lambda row: 'Kearney' not in str(row['Library Name'])"
    - "lambda row: 'ITS2' not in str(row['Library Name'])"
    - "lambda row: str(row['Plant Body Site [sample]']) != 'Soil'"
  treatment_col: "Watering Regm [sample]"
  treatments:
    "Drought": "Drought"
    "Control": "Control"
  host_col: "Isolation Source [sample]"
  hosts:
    "Zea mays": "PACMAD clade"
    "Triticum turgidum": "BOP clade"
    "Triticum monococcum": "BOP clade"
    "Triticum aestivum": "BOP clade"
    "Sorghum laxiflorum": "PACMAD clade"
    "Sorghum bicolor": "PACMAD clade"
    "Sorghastrum nutans": "PACMAD clade"
    "Solanum lycopersicum": "Asterids"
    "Secale cereale": "BOP clade"
    "Pennisetum glaucum": "PACMAD clade"
    "Miscanthus sinensis": "PACMAD clade"
    "Hordeum vulgare": "BOP clade"
    "Festuca arundinacea": "BOP clade"
    "Eragrostis tef": "PACMAD clade"
    "Brachypodium distachyon": "BOP clade"
    "Bothriochloa bladhii": "PACMAD clade"
    "Avena sativa": "BOP clade"
  hosts_ungrouped:
    "Zea mays": "Zea mays"
    "Triticum turgidum": "Triticum turgidum"
    "Triticum monococcum": "Triticum monococcum"
    "Triticum aestivum": "Triticum aestivum"
    "Sorghum laxiflorum": "Sorghum laxiflorum"
    "Sorghum bicolor": "Sorghum bicolor"
    "Sorghastrum nutans": "Sorghastrum nutans"
    "Solanum lycopersicum": "Solanum lycopersicum"
    "Secale cereale": "Secale cereale"
    "Pennisetum glaucum": "Cenchrus americanus"
    "Miscanthus sinensis": "Miscanthus sinensis"
    "Hordeum vulgare": "Hordeum vulgare"
    "Festuca arundinacea": "Lolium arundinaceum" # synonyms
    "Eragrostis tef": "Eragrostis tef"
    "Brachypodium distachyon": "Brachypodium distachyon"
    "Bothriochloa bladhii": "Bothriochloa bladhii"
    "Avena sativa": "Avena sativa"
  location: "California"
  soil_type: "Field"
  primers: "341F,785R"
  regions: "V3-V4"

kost2024microbial:
  amplicon_length: 300
  filters:
    - "lambda row: str(row['Isolation Source [sample]']) != 'soil'"
  treatment_col: "Treatment_all"
  treatments:
    "Drought": "Drought"
    "Watered": "Control"
  host_col: "Host [sample]"
  hosts:
    "Echinochloa esculenta": "PACMAD clade"
    "Panicum miliaceum": "PACMAD clade"
    # Misspelled in the metadata
    "Penisetum glaucum": "PACMAD clade"
    "Setaria italica": "PACMAD clade"
    "Sorghum bicolor": "PACMAD clade"
  hosts_ungrouped:
    "Echinochloa esculenta": "Echinochloa esculenta"
    "Panicum miliaceum": "Panicum miliaceum"
    "Penisetum glaucum": "Cenchrus americanus"
    "Setaria italica": "Setaria italica"
    "Sorghum bicolor": "Sorghum bicolor"
